version: "3.7"
services:
  mysql:
    image: public.ecr.aws/bitnami/mysql:5.7
    environment:
      MYSQL_USER: blackmarket_puzzler
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: blackmarket
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
  phpmyadmin:
    image: public.ecr.aws/bitnami/phpmyadmin:latest
    restart: always
    ports:
      - 8081:8080
    environment:
      - DATABASE_HOST=mysql
      - PHP_UPLOAD_MAX_FILESIZE=100M
      - PHP_POST_MAX_SIZE=100M
      - PHPMYADMIN_ALLOW_ARBITRARY_SERVER=true
    depends_on:
      - mysql
